SUCCESS = 0

#For main.py
INCORRECT_FORMAT_ERROR = 1
INCORRECT_LABEL_FILE_ERROR = 2
INCORRECT_VIDEO_FILE_ERROR = 3

#For timeFunc.py
INVALID_TYPE_OF_TIME_ERROR = 4
INVALID_TIME_FORMAT_ERROR = 5
INVALID_TIME_DIFFERENCE_ORDER_ERROR = 6

#For recognize.py
VIDEO_TOO_SHORT_ERROR = 7

#For fileHandler.py
DB_CSV_OUT_OF_SYNC_ERROR = 8
INCORRECT_DB_FILE_ERROR = 9
